### ISSUE TITLE
When I installed the `vscode` Go plugin in the container I ran into a problem.

### ISSUE THREAD

**Issue by reallEz** [FrankFang/oh-my-docker#1]
Open workspace, and install plugin `Go`, then i saw:
![image](https://user-images.githubusercontent.com/85923172/149306413-83b7ba4b-df5f-4c1e-8d53-42ad96c8ef1b.png)

Plugin is 
![image](https://user-images.githubusercontent.com/85923172/149306706-4c3217cf-ce08-4f70-849a-872d524068de.png)

**Comment by FrankFang** [comment]
请提供更详细的信息，比如操作系统版本，完整的日志。
